FROM node:24-alpine AS build

WORKDIR /app

RUN apk add --no-cache zip

ARG VITE_API_BASE_URL
ARG VITE_WEB_ORIGIN
ARG TRUTHSHIELD_EXTENSION_WEB_ORIGIN
ARG TRUTHSHIELD_EXTENSION_API_ORIGIN
ARG VITE_EVIDENCE_UPLOAD_ENDPOINT
ARG VITE_EVIDENCE_UPLOAD_FIELD
ARG VITE_EVIDENCE_UPLOAD_URL_PATH
ARG VITE_EVIDENCE_UPLOAD_MAX_MB
ARG VITE_EVIDENCE_IMAGE_HOST_URL
ARG VITE_EVIDENCE_CLOUD_DRIVE_URL

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_WEB_ORIGIN=${VITE_WEB_ORIGIN}
ENV TRUTHSHIELD_EXTENSION_WEB_ORIGIN=${TRUTHSHIELD_EXTENSION_WEB_ORIGIN}
ENV TRUTHSHIELD_EXTENSION_API_ORIGIN=${TRUTHSHIELD_EXTENSION_API_ORIGIN}
ENV VITE_EVIDENCE_UPLOAD_ENDPOINT=${VITE_EVIDENCE_UPLOAD_ENDPOINT}
ENV VITE_EVIDENCE_UPLOAD_FIELD=${VITE_EVIDENCE_UPLOAD_FIELD}
ENV VITE_EVIDENCE_UPLOAD_URL_PATH=${VITE_EVIDENCE_UPLOAD_URL_PATH}
ENV VITE_EVIDENCE_UPLOAD_MAX_MB=${VITE_EVIDENCE_UPLOAD_MAX_MB}
ENV VITE_EVIDENCE_IMAGE_HOST_URL=${VITE_EVIDENCE_IMAGE_HOST_URL}
ENV VITE_EVIDENCE_CLOUD_DRIVE_URL=${VITE_EVIDENCE_CLOUD_DRIVE_URL}

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run package:extension

FROM nginx:1.29-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
